### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RegiByte** [node-ffi-napi/ref-napi#16]
Hello guys, so i'm running my tests suite with jest and i'm getting an
`RangeError: Maximum call stack size exceeded` error testing `argon2-ffi` package which has this as a dependency,

This is the exact error message:

```
Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at debug (node_modules/ref-napi/node_modules/debug/src/common.js:1:1)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:741:3)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:11)
```

And when i check that out it looks like we have an infinite loop error, please correct me if i'm wrong because i really don't know exacly what is happening on this lines:

ref.js:742
```javascript
exports.writePointer = function writePointer (buf, offset, ptr) {
  debug('writing pointer to buffer', buf, offset, ptr);
  exports._writePointer(buf, offset, ptr); // This line is calling itself forever or am i wrong ?
  exports._attach(buf, ptr);
};
```

and then on the ref.js:721
```javascript
exports._writePointer = exports.writePointer;
```

**Comment by prurph** [comment]
Also experiencing this issue.

**Comment by Audio** [comment]
Hi, #metoo

Steps to reproduce:
```
require('ref-napi')
delete require.cache[require.resolve('ref-napi')]
require('ref-napi')
```
Node.js version: v12.14.1

**Comment by ordoghl** [comment]
Same here. Blows Jest test as a dependency of encrypt-xlsx (through ffi-napi). Node.js version: 12.15.0

**Comment by acdibble** [comment]
I ran into this using jest tests. It seems to relate to how jest mocks out importing dependencies. I put an `afterEach` hook in the tests with `jest.restoreAllMocks()` and that resolved the issue.

It looks like for whatever reason, this isn't properly executed every time the module is required:
![image](https://user-images.githubusercontent.com/21286068/86923903-fcabdf00-c12e-11ea-86d3-22b104b6c51b.png)

So this turns into an infinitely recursive call:
![image](https://user-images.githubusercontent.com/21286068/86923968-1a794400-c12f-11ea-850d-b72dd9cde0c4.png)
